# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dos2unix <- function(fin_path, fout_path) {
    invisible(.Call('_supeRbaits_dos2unix', PACKAGE = 'supeRbaits', fin_path, fout_path))
}

getBaits <- function(db_path, df) {
    .Call('_supeRbaits_getBaits', PACKAGE = 'supeRbaits', db_path, df)
}

getChromLengths <- function(path) {
    .Call('_supeRbaits_getChromLengths', PACKAGE = 'supeRbaits', path)
}

removeNLs <- function(fin_path, fout_path) {
    invisible(.Call('_supeRbaits_removeNLs', PACKAGE = 'supeRbaits', fin_path, fout_path))
}

sampleBaits <- function(chrom_info, exclusions, regions, targets, size, regions_tiling, targets_tiling, regions_prop, targets_prop) {
    .Call('_supeRbaits_sampleBaits', PACKAGE = 'supeRbaits', chrom_info, exclusions, regions, targets, size, regions_tiling, targets_tiling, regions_prop, targets_prop)
}

