# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getBaits <- function(gen_path, bait_df, max_memo = 5L) {
    .Call('_supeRbaits_getBaits', PACKAGE = 'supeRbaits', gen_path, bait_df, max_memo)
}

getChromLengths <- function(path) {
    .Call('_supeRbaits_getChromLengths', PACKAGE = 'supeRbaits', path)
}

